# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-23 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_picture_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='is_favorite',
        ),
    ]
